In [1]:
#Numpy is the core library for scientific computing in python.

import numpy as np

In [2]:
my_list=[1,2,3,4,5]
x = np.array(my_list)
print(x)

[1 2 3 4 5]


In [3]:
type(x)

numpy.ndarray

In [4]:
x = np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [6]:
#multi-dimentional array
x = np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
x.size

6

In [8]:
x.shape

(2, 3)

In [9]:
x.ndim

2

In [10]:
x.dtype

dtype('int64')

In [11]:
y=x.astype('int')
y

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
#built-in functions for creating arrays
x = np.zeros((3,2))
x

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
x = np.ones((3,2))
x

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [15]:
x = np.eye(4)
x


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
x = np.diag((1,2,3))
x

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [17]:
x=np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
x=np.linspace(0,3,7)

x

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. ])

In [20]:
len(x)

7

In [21]:
[1.2]*3

[1.2, 1.2, 1.2]

In [22]:
x = np.array([1.2]*3)
x

array([1.2, 1.2, 1.2])

In [23]:
x=np.repeat([1,2],3)
x

array([1, 1, 1, 2, 2, 2])

In [24]:
#stacking
ones = np.ones((3,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
twos=ones*2
twos

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [26]:
x=np.vstack([ones,twos])
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [27]:
x=np.hstack([ones,twos])
x

array([[1., 1., 1., 1., 2., 2., 2., 2.],
       [1., 1., 1., 1., 2., 2., 2., 2.],
       [1., 1., 1., 1., 2., 2., 2., 2.]])

In [29]:
#Basic stats and linear algebra 

w=np.array([[3,4],[1,2]])
z=np.array([[5,6],[7,8]])

z

array([[5, 6],
       [7, 8]])

In [30]:
z.sum()

np.int64(26)

In [32]:
w+z

array([[ 8, 10],
       [ 8, 10]])

In [33]:
w*z

array([[15, 24],
       [ 7, 16]])

In [34]:
z

array([[5, 6],
       [7, 8]])

In [35]:
x

array([[1., 1., 1., 1., 2., 2., 2., 2.],
       [1., 1., 1., 1., 2., 2., 2., 2.],
       [1., 1., 1., 1., 2., 2., 2., 2.]])

In [36]:
x.min()

np.float64(1.0)

In [37]:
x.max()

np.float64(2.0)

In [38]:
x.mean()

np.float64(1.5)

In [39]:
x.var()

np.float64(0.25)

In [40]:
x.std()

np.float64(0.5)

In [41]:
x.argmin()

np.int64(0)

In [42]:
x.argmax()

np.int64(4)

In [43]:
#matrix and linear algebra
A=np.array([[1,2,3],[4,5,6]])

A

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
A.shape

(2, 3)

In [45]:
A.mean()

np.float64(3.5)

In [46]:
A.max()

np.int64(6)

In [47]:
A.argmax()

np.int64(5)

In [48]:
#reshape.resize

A

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
x=np.array([1,2,3,4,5,6])
x.resize(2,3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
x.reshape(2,3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
x=np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [57]:
x[2]

np.int64(2)

In [ ]:
x[2,