In [2]:
import numpy as np
arr = np.arange(1, 11)

print(np.sqrt(arr))
print(np.exp(arr))


[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04]


In [3]:
arr = np.array([10, 20, 30, 40, 50])

print(np.mean(arr))    # 30.0
print(np.median(arr))  # 30.0
print(np.std(arr))     # 14.14 (approx)

30.0
30.0
14.142135623730951


In [6]:
arr = np.array([[1, 5, 3], [4, 2, 6]])

print(np.min(arr, axis=1))  # [1 2]
print(np.max(arr, axis=1))  # [5 6]

[1 2]
[5 6]


In [7]:
arr = np.array([1, 10, 100])

print(np.log(arr))

[0.         2.30258509 4.60517019]


In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(np.sum(arr, axis=0))  # [5 7 9]

[5 7 9]


In [9]:
arr = np.random.rand(100)

print(np.mean(arr))  # ~0.5 (random)
print(np.var(arr))   # ~0.08 (random)

0.4668710180650956
0.07504113679785514


In [10]:
arr = np.array([10, 20, 30, 40, 50])

z = (arr - np.mean(arr)) / np.std(arr)
print(z)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
