In [1]:
import numpy as np

sales = np.array([
    [101, 1200, 200, 5],
    [102, 1500, 300, 8],
    [103, 1800, 400, 10],
    [104, 1000, 150, 4],
    [105, 2200, 500, 12]
])

In [2]:
total_revenue = np.sum(sales[:,1]) #1. Find total revenue
print(total_revenue)

7700


In [3]:
total_profit = np.sum(sales[:,2]) #2. Find total profit
print(total_profit)

1550


In [4]:
avg_revenue = np.mean(sales[:,1])#3. Find average revenue
print(avg_revenue)

1540.0


In [5]:
avg_profit = np.mean(sales[:,2]) #4. Find average profit
print(avg_profit)

310.0


In [6]:
highest_revenue = np.max(sales[:,1]) #5. Find highest revenue
print(highest_revenue)

2200


In [7]:
lowest_revenue = np.min(sales[:,1])#6. Find lowest revenue
print(lowest_revenue)

1000


In [8]:
index = np.argmax(sales[:,2]) #7. Find customer with maximum profit
customer = sales[index,0]

print(customer)

105


In [9]:
index = np.argmin(sales[:,2]) #8. Find customer with minimum profit
customer = sales[index,0]

print(customer)

104


In [10]:
profit_margin = (sales[:,2] / sales[:,1]) * 100 #9. Calculate profit margin for each customer
print(profit_margin)

[16.66666667 20.         22.22222222 15.         22.72727273]


In [11]:
total_orders = np.sum(sales[:,3]) #10. Find total orders
print(total_orders)

39


In [12]:
avg_orders = np.mean(sales[:,3]) #11. Find average orders
print(avg_orders)

7.8


In [13]:
revenue_per_order = sales[:,1] / sales[:,3] #12. Find revenue generated per order
print(revenue_per_order)

[240.         187.5        180.         250.         183.33333333]


In [14]:
high_revenue_customers = sales[sales[:,1] > 1500] #13. Find customers with revenue greater than 1500

print(high_revenue_customers)

[[ 103 1800  400   10]
 [ 105 2200  500   12]]


In [15]:
count = np.sum(sales[:,2] > 300) #14. Count customers with profit above 300

print(count)

2


In [16]:
std_revenue = np.std(sales[:,1]) #15. Find standard deviation of revenue

print(std_revenue)

427.0831300812524


In [17]:
sorted_sales = sales[sales[:,1].argsort()] #16. Sort customers by revenue

print(sorted_sales)

[[ 104 1000  150    4]
 [ 101 1200  200    5]
 [ 102 1500  300    8]
 [ 103 1800  400   10]
 [ 105 2200  500   12]]


In [18]:
median_revenue = np.median(sales[:,1]) #17. Find median revenue

print(median_revenue)

1500.0


In [19]:
cumulative_revenue = np.cumsum(sales[:,1]) #18. Calculate cumulative revenue

print(cumulative_revenue)

[1200 2700 4500 5500 7700]


In [20]:
correlation = np.corrcoef(sales[:,1], sales[:,2]) #19. Find correlation between revenue and profit

print(correlation)

[[1.         0.99829363]
 [0.99829363 1.        ]]
