# Numpy array and basics

In [1]:

import numpy as np

## creating array from list

In [2]:
a = [1, 2, 3] #python list
b = [4, 5, 6]

print(a + b)

[1, 2, 3, 4, 5, 6]


In [3]:
import numpy as np

a = np.array([1, 2, 3]) #numpy array
b = np.array([4, 5, 6])

print(a + b)

[5 7 9]


In [6]:

py_list = [1, 2, 3]
print("Python list multiplication ", py_list * 2)


np_array = np.array([1, 2, 3]) #element wise multiplication
print("Python array multiplication ", np_array * 2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time: ", time.time() - start)

Python list multiplication  [1, 2, 3, 1, 2, 3]
Python array multiplication  [2 4 6]

 List operation time:  0.19263458251953125

 Numpy operation time:  0.012367963790893555


## When to Use Which

### Use list when:

- Storing mixed data types
- Frequent insertions/deletions
- General Python programming


### Use NumPy array when:

- Doing math/scientific computing
- Working with matrices/vectors
- Handling large datasets
- Need speed and efficiency

In [8]:
#creating array from scratch
zeros = np.zeros((3, 4))
print("zeros array: \n", zeros)

ones = np.ones((2, 3))
print("one array: \n", ones)

full = np.full((2, 2), 7)
print("full array: \n", full)

random = np.random.random((2, 3))
print("random array: \n", random)

sequence = np.arange(0, 11, 2)
print("sequnce array: \n", sequence)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
one array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.17697783 0.44176539 0.26738394]
 [0.9996403  0.0873134  0.25456779]]
sequnce array: 
 [ 0  2  4  6  8 10]


### Vector vs Matrix vs Tensor


In [9]:
import numpy as np

v = np.array([2, 4, 6])
print(v.shape)

(3,)


In [10]:
m = np.array([
    [1,2,3],
    [4,5,6]
])

print(m.shape)

(2, 3)


In [ ]:
[
 [
   [1,2],
   [3,4]
 ],
 [
   [5,6],
   [7,8]
 ]
]